### ISSUE TITLE
Is Https server is mandatory?

### ISSUE THREAD

**Issue by fnajmee** [jeffreykemp/clicksend-plsql-api#12]
Hi,
i am facing issue "Network access denied by ACL ORA-24247". my Oracle Serv er is http. will it work only with https server?

i completed all the steps and set the the account as well.

![ACL Error](https://user-images.githubusercontent.com/61585787/83324982-36610e80-a282-11ea-98b9-d11bd73bb6f7.png)

**Comment by jeffreykemp** [comment]
Access to the clicksend API must be by Secure HTTP - but if you set up a reverse proxy you can avoid the need to set up your database with https access. Refer to the wiki for instructions for Method 2: https://github.com/jeffreykemp/clicksend-plsql-api/wiki/installation
